### ISSUE TITLE
Invisible clothing

### ISSUE THREAD

**Issue by c-reckless** [New-Chance-RP/Feedback#145] opened 2020-05-24 16:11 UTC
<h2>What bug have you found?</h2>

A couple of items in the clothing store are not rendering, making the character becoming invisible in some areas.

<h2>What do you expect should happen?</h2>

Clothing shows on the character 

<h2>Anything to support your bug report?</h2>

https://ibb.co/vkp7SHW

**Comment by Senlarus** [comment] 2020-05-25 05:00
Was unable to reproduce. Might be a new character bug?

**Comment by c-reckless** [comment] 2020-05-26 15:24
Tested again today on a brand new character, here's one of the items:

https://ibb.co/3kfLLvM

**Comment by Senlarus** [comment] 2020-05-31 05:30
I haven't seen any pantsless people in the city for a while now. Anyone still seeing this bug or was it fixed by the clothing store update I did?

**Comment by Senlarus** [comment] 2020-06-10 05:01
We're replacing our skin system with a new one. Once I announced it is ready we will have people bug test it. This issue may be non-existent now due to this so I'm closing for now.

**Closed by Senlarus** 2020-06-10 05:01 UTC
Labels: Bug
