### ISSUE TITLE
Hat and glasses issue.

### ISSUE THREAD

**Issue by ArnieBIB** [New-Chance-RP/Feedback#481] opened 2020-09-01 15:57 UTC
<h2>What bug have you found?</h2>

When getting punched your hat and glasses (if being worn) will fall off which is fine, however when you want to put them back on it says it is unable to put them back on.

<h2>What do you expect should happen?</h2>

I wish after being punched and hats/glasses being knocked off, you should be able to do /hat or /glasses to put the accessories back on instead of saying "unable". 

<h2>Anything to support your bug report?</h2>

Just throughout city, happened many times and I have always had to clock into a job and then clock out to get my accessories back on my person.

**Comment by Senlarus** [comment] 2020-09-06 16:37
Duplicate of #465.

**Closed by Senlarus** 2020-09-06 16:37 UTC
Labels: Bug
