### ISSUE TITLE
Dodge Durango

### ISSUE THREAD

**Issue by oMrWz** [New-Chance-RP/Feedback#703] opened 2020-12-20 08:27 UTC
What bug have you found? Paintjob changing different colors/textures and its very weak as well even with armor it breaks down like its made of aluminum

What do you expect should happen? Hopefully get fixed asap

Anything to support your bug report? No

Have you got any evidence to help prove the bug, a video or picture etc? Its Suppose to be all black 

![Screenshot (146)](https://user-images.githubusercontent.com/76278805/102708802-271fcd80-4273-11eb-9b3c-7de86d492b9d.png)

![Screenshot (147)](https://user-images.githubusercontent.com/76278805/102708808-2e46db80-4273-11eb-9333-99f09add4aaa.png)

![Screenshot (149)](https://user-images.githubusercontent.com/76278805/102708811-33a42600-4273-11eb-9c2d-0ebfcd63c1d6.png)

**Comment by driftoooo** [comment] 2020-12-20 10:41
Duplicate of #672, closing issue.

**Closed by driftoooo** 2020-12-20 10:41 UTC
Labels: Bug
