### ISSUE TITLE
Strange Garbage Job Bug

### ISSUE THREAD

**Issue by Monster-Duck** [New-Chance-RP/Feedback#196] opened 2020-05-26 06:09 UTC
<h2>What bug have you found?</h2>

I honestly am not quite sure what happened in this garbage gathering scenario, but I put in all my bags; the truck was still open and another guy was able to put in a bag which then payed me.

<h2>What do you expect should happen?</h2>

After putting all the dumpsters bags in the trash the truck should have closed and I been able to leave.

<h2>Anything to support your bug report?</h2>

https://medal.tv/clips/25038842/d1337f91alaK

**Comment by Senlarus** [comment] 2020-05-31 03:56
Looks like that might happen when two drugs have the same dumpster at the same time. Will have to try to reproduce after my recent changes to attempt to fix the red circle issue.

**Comment by Senlarus** [comment] 2020-06-01 03:31
This should have been fixed in most recent red circle glitch. Closing, track all garbage job issues on #207 now please.

**Closed by Senlarus** 2020-06-01 03:31 UTC
Labels: Bug
