### ISSUE TITLE
Torros needs a fix 9th gear issue

### ISSUE THREAD

**Issue by meraj301** [New-Chance-RP/Feedback#579] opened 2020-10-30 16:12 UTC
The Torros vehicle has a issue where it goes into 9th gear whenever you come to a complete stop and try to accelerate again. The only fix for this is to reverse, then drive putting it back in 1st. When the vehicle is in 9th gear it doesn't really move much, and it causes a pain to drive the vehicle I paid so much for.

**Comment by s1Sabz** [comment] 2020-10-31 15:14
you can fix this by removing the transmission ( the transmission doesn't make it fast anyway so it makes no difference)

**Comment by Senlarus** [comment] 2020-11-02 06:40
Duplicate of #556

**Closed by Senlarus** 2020-11-02 06:40 UTC
