### ISSUE TITLE
69' Charger Sound/Handling

### ISSUE THREAD

**Issue by ABroHaam** [New-Chance-RP/Feedback#776] opened 2021-01-18 23:31 UTC
<h2>Request to change the 69' Charger Sounds/Handling</h2>

**3) - Vehicle changes -** *What changes you want think should be made.*

The traction of the 69' Charger is very underwhelming. I think that with the tires that are on this vehicle they are basically drag slicks which would give it much more traction than it has. Cornering would obviously be wide and swooping not quick in the corners at all but this thing is built like a drag car with a big block blown V8 and drag slicks in the rear. The sound of the 69' Charger IMO currently doesn't line up with the power plant it's using. It's a big block blown V8 Chevy motor and these things in that state sound nasty. 

<h2>Why are you making this request?</h2>

Personally, I think that the car would work much better with the sound that the hellcat/ Silverado use. Its a raw in your face sound, Which fits this power train more.

**Comment by driftoooo** [comment] 2021-01-18 23:42
Basically a duplicate of #668, closing issue.

**Closed by driftoooo** 2021-01-18 23:42 UTC
Labels: Vehicles
