### ISSUE TITLE
Locked Vehicle, Unlocked Trunk

### ISSUE THREAD

**Issue by SuperCShe** [New-Chance-RP/Feedback#478] opened 2020-09-01 00:44 UTC
<h2>What bug have you found?</h2>

When you have a vehicle and you exit and lock it, the truck is still accessible to anyone.

<h2>What do you expect should happen?</h2>

If you lock a vehicle, your trunk should also be locked.

<h2>Anything to support your bug report?</h2>

I am streaming as I usually do and I caught it happen there.
https://clips.twitch.tv/EntertainingMistyHawkJonCarnage

**Comment by Senlarus** [comment] 2020-09-02 02:21
Can't reproduce this on our dev machines. Can you check it to see if it's still happening? I assume you stole a vehicle at gunpoint to get the keys and then locked it. Could you look more into this? Maybe Honton had the keys and had it locked but you could still get into the trunk? Could he still get into it while it was locked?

**Comment by Senlarus** [comment] 2020-09-15 06:12
Closing due to no further information and inability to reproduce it.

**Closed by Senlarus** 2020-09-15 06:12 UTC
Labels: Bug
