### ISSUE TITLE
PDM Car Sale

### ISSUE THREAD

**Issue by Monster-Duck** [New-Chance-RP/Feedback#103] opened 2020-05-10 17:57 UTC
<h2>What bug have you found?</h2>

Carjack a vehicle and then try to sell it behind PDM.

<h2>What do you expect should happen?</h2>

It should give some sort of denial message for stolen vehicles.
<h2>Anything to support your bug report?</h2>

Nothing at all.

**Comment by Senlarus** [comment] 2020-05-13 03:39
Duplicate of #69

**Closed by Senlarus** 2020-05-13 03:39 UTC
Labels: Bug
